import Head from 'next/head';
import WithLayout from '@/components/WithLayout';
import HomeContainer from '@/containers/Home';

export default function Home() {
  return (
    <>
      <Head>
        <title>Restaurant App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WithLayout>
          <HomeContainer />
        </WithLayout>
      </main>
    </>
  );
}
