import ProductDetailsContainer from '@/containers/ProductDetails';
import Head from 'next/head';
import React from 'react';

const ProductDetails = () => {
  return (
    <>
      <Head>
        <title>Restaurant App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mx-auto max-w-[640pt]' >
        <ProductDetailsContainer />
      </main>
    </>
  );
};

export default ProductDetails;
